#!/bin/sh

DWL_LOCK_BACKGROUND=$DWL_BACKGROUND

dwlb -font "Source Code Pro:size=10:antialias=true:style=Medium:hintstyle=3:rgba=none" <&0 &

/usr/libexec/xdg-desktop-portal-wlr || true &
/usr/libexec/xdg-desktop-portal-gtk || true &
/usr/libexec/xdg-desktop-portal || true &

pipewire || true &
wireplumber || true &
swaybg --output '*' --mode fill --image "$DWL_BACKGROUND" || true &

swayidle -w \
	timeout 120 "wl-lock" \
	timeout 240 "wlopm --off '*'" \
	resume "wlopm --on '*'" \
	&

(
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway \
|| \
dbus-update-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
) &
