#!/bin/sh

export DWL_LOCK_BACKGROUND="$DWL_BACKGROUND"

export XDG_CURRENT_DESKTOP=wlroots
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=wlroots

printf "xdg-desktop-portal-wlr xdg-desktop-portal-gtk xdg-desktop-portal wireplumber pipewire\n" | tr ' ' '\n' | while read __file; do
	killall $__file
done

dbus-launch dwl -d -s dwlrc
